sudo: required
services:
 - docker

before_install:
 - docker build -t lfbds/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run lfbds/react-test npm test -- --coverage

after_success:
 - docker build -t lfbds/multi-client ./client
 - docker build -t lfbds/multi-nginx ./nginx
 - docker build -t lfbds/multi-server ./server
 - docker build -t lfbds/multi-worker ./worker

 - echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin

 - docker push lfbds/multi-client
 - docker push lfbds/multi-nginx
 - docker push lfbds/multi-server
 - docker push lfbds/multi-worker
